### PR TITLE
Large changes

### PR DESCRIPTION
**Pull request by kitskub**
Separate SpoutWorld into SpoutWorld and SpoutServerWorld
Move some stuff from SpoutEngine to SpoutServer

SpoutAPI: https://github.com/SpoutDev/SpoutAPI/pull/559
Vanilla: https://github.com/Vanilla/Vanilla/pull/626

Signed-off-by: Jack Huey kitskub@gmail.com

### CODE REVIEW

**Comment by macalinao** [comment]
Squash into one commit

**Comment by kitskub** [comment]
No ian, i have gotten permission.

**Comment by windy1** [comment]
Even so, it needs to be signed off.

**Comment by kitskub** [comment]
Both commits?

**Comment by windy1** [comment]
Yes @kitskub

**Pull request merged**
