### PR TITLE
Possible fix for NPE while polling

### PR DESCRIPTION
**Pull request by Top-Cat**

### CODE REVIEW

**Comment by Raphfrk** [comment]
Hmm, am probably going to be changing that code again soon again.  It was right when I had it doing resyncing :).

**Comment by tips48** [comment]
Yea, it got screwed up at build 22 i think. maybe 21, i think 22

**Comment by Afforess** [comment]
Did this pull fix it?

**Comment by tips48** [comment]
From what i've seen, yes. can't be sure though

**Pull request merged**
