### PR TITLE
Added Workbench interaction handling

### PR DESCRIPTION
**Pull request by lopcode**
Right clicking workbench works as expected, window pops up, window handling on the backend is done as expected.

Workbench crafting still not implemented - someone smarter than me should take a look at WindowClickMessageHandler to call craft() appropriately.

CraftingInventory.craft() is not inventory agnostic - needs looking at so it works for different types of inventory.

### CODE REVIEW

**Comment by ZNickq** [comment]
Nice! :)

**Comment by narrowtux** [comment]
Is your copy on a FAT-Volume? I'd strongly advise against that, because you changed all the file modifiers to 100775. This will cause strange effects on the console because it thinks that they are executeable.

**Comment by lopcode** [comment]
I'm on Windows, NTFS, with NetBeans. I have absolutely no idea why the file modes are changing :S

**Comment by zml2008** [comment]
This would create a StackOverflowException any time someone placed a workbench. Did you even test this?

**Comment by lopcode** [comment]
... it works fine for me? EDIT: Confirmed, there's no exceptions.

**Comment by narrowtux** [comment]
It generates this exception when I close the Inventory screen:
http://pastebin.com/m2SYNy4y

**Comment by lopcode** [comment]
Someone else was looking at fixing the close window bug in the channel - I didn't touch it.

**Comment by ZNickq** [comment]
It was me ;) 
Problem is,  i am not sure where in spout the opening of windows takes place...

**Comment by zml2008** [comment]
I removed some things, and the inventory + block physics APIs are probably going to be refactored a ton. Also, your formatting is wrong. You can look at every other source file in the project for correct examples. For now I'll be closing this.

**Pull request closed without merging**
