### PR TITLE
Ran FindBugs on Spout

### PR DESCRIPTION
**Pull request by TomyLobo**
The changes from this last commit should not be pulled, but inspected by the respective developers.

I didn't sign it off to hint at this.

I also made one for SpoutAPI: https://github.com/SpoutDev/SpoutAPI/pull/230
and one for Vanilla: https://github.com/VanillaDev/Vanilla/pull/213

### CODE REVIEW

**Comment by windy1** [comment]
These should be squashed into one commit.

**Comment by TomyLobo** [comment]
no, I want the fixes to be looked at by the developers
Commits 2 and 3 are things that really shouldn't happen to anyone trusted with such a project.
Commit 2 is the result of someone being unaware of object array cast rules
Commit 3 is apparently the result of someone uncritically applying quickfixes
Commit 4 is just an oversight
Commit 5 needs to be looked at by the developers and then discarded (it only adds comments)

**Comment by TomyLobo** [comment]
ok, that leaves only commit #5, to be inspected by some people :)

**Comment by Salynne** [comment]
Closing these, and making some probably permanent issues for the repos as a reminder to keep up to date on this.

http://issues.spout.org/browse/SPOUT-66

**Pull request closed without merging**
