### PR TITLE
Trees, netbeans

### PR DESCRIPTION
**Pull request by md-5**
Redo of that

### CODE REVIEW

**Comment by Rycochet** [comment]
Actually - nb-configuration.xml should be in .gitignore ;-)

**Comment by md-5** [comment]
Nope.
@Wulfspider wants it. Planning to add formatting rules for all the ide's. I didn't even stage it.

**Comment by lukespragg** [comment]
@Rycochet we're trying to help with some of the formatting automatically.

**Comment by Rycochet** [comment]
Ooh, nice - now all we need to do is make sure everyone is using Netbeans and not that nasty Eclipse thingy... :-P

**Comment by md-5** [comment]
I wish
Might take a look at eclipse formatting
Eclipse in general hates me

**Comment by Top-Cat** [comment]
Why don't we add ide-specifc files for all the ides, let me go do that

**Comment by md-5** [comment]
top-cat I done eclipse already

**Comment by Top-Cat** [comment]
Please make sure you cover BlueJ, JCreator, JBuilder, DrJava, JDeveloper, and IntelliJ. We need as much bloat as possible!

**Comment by Rycochet** [comment]
/me wonders how to set the options for notepad++, can't find anything, so considers including a full copy of it instead...

**Comment by Top-Cat** [comment]
Yeah, the portable version with correct settings should do.

**Comment by Top-Cat** [comment]
Maybe we should create a second folder with the entire repository with windows line breaks for the people who use notepad?

**Comment by Rycochet** [comment]
Nah - too complex - what we want is to xml encode the entire source, then have a set of tools for every platform to convert them back and forth - that way it's all enterprise-like...

**Comment by Top-Cat** [comment]
> **Rycochet**
> suggesting the inclusion of a complete livecd linux distro so everyone is working the same way ;-)

+1
We should have our own with eclipse bundled so everyone has the same

**Comment by Rycochet** [comment]
True - since I reckon that's the only way anyone can actually get Eclipse to run if it's included in it's own custom linux distro...

**Comment by RoyAwesome** [comment]
So, I have this entire CPU architecture that I built and fabricated on my spare time, perhaps you guys can use it.

**Comment by Rycochet** [comment]
Does it require an anthill to run perhaps? Because it's getting a little cold for the poor things now... ;-)

**Comment by Top-Cat** [comment]
My fridge has been running for 12 hours, it's now 10km away and I'm hungry :(

**Comment by macalinao** [comment]
Please get rid of nb-configuration, it's making my settings wrong.

**Pull request merged**
