### PR TITLE
Server/Client matching packet lengths

### PR DESCRIPTION
**Pull request by Raphfrk**
This matches the packet lengths for server and client.  

The server uses getNumBytes() via a(), which calls getNumBytes().  However, the client adds 8 to getNumBytes() and returns that as getPacketSize().

This may not be the cleanest fix.  Another option would be to change writePacketData() so that it calls getNumBytes() and leave getPacketSize() return the full packet size.

### CODE REVIEW

**Comment by Raphfrk** [comment]
Updated so that it subtracts 8 for the payload length field and getPacketSize() is back to giving the full packet size.

**Comment by Afforess** [comment]
I don't see any changes to getPacketSize()

**Comment by Raphfrk** [comment]
Sorry, the original pull changed line 25 to "return packet.getNumBytes();", so the reduction by 8 happened there.

The updated version has the reduction happening in WritePacketData.  That way getPacketSize() is correct (which since it is a method for Packet probably should be the full length).

**Comment by Raphfrk** [comment]
Ofc, this all depends on what the length field was supposed to mean.

For the server, it gives payload length, but for the client, it gave packet length (so payload + 8).

**Pull request merged**
