### PR TITLE
Implemented /give.

### PR DESCRIPTION
**Pull request by spacechase0**
It crashes the client whenever I try to give something that's a GenericTool or GenericWeapon from Vanilla. Not sure why, but sometimes it tells me it's a NullPointerException.

Signed-off-by: Chase W chasew@silkweaver.com

### CODE REVIEW

**Comment by Zidane** [comment]
Looks pretty good...I want to take this farther though and allow strings to be used as well.

Idea is you could do /give NinjaZidane wool 1 which would give the first registered material named "Wool" to the player...but what if two plugins have the same material named wool? /give NinjaZidane wool:1 1 would suffice I think. Only issue I think is when you have a block that has different states (aka redwool)...personally I think we can just create a new block for them and you can do /give NinjaZidane redwool 1 then.

Any ideas from anyone else?

**Comment by spacechase0** [comment]
Strings actually do work a little ([see here](https://github.com/spacechase0/Spout/commit/a57e2dee4ca9e0abc0ce1a082f2c476bcb7044dc#L0R110)), but any block with a space in it (like Red Mushroom) won't work, since arguments are separated by spaces.

It looks [from here](https://github.com/SpoutDev/SpoutAPI/blob/master/src/main/java/org/spout/api/material/GenericItemMaterial.java#L43) that the name and display name use the same string. Maybe replacing spaces in name (but not display name) would fix that.

Maybe another way for specifying which plugin would be prefixing the plugin name, like vanilla:wool?

**Comment by SonnyX** [comment]
A way to make items with spaces work is check the amount of Integers and use the latest for the amount and process the first 2 the same as you normally would.

**Comment by windy1** [comment]
Ehm... this should be in Vanilla probably.

**Comment by spacechase0** [comment]
How come? I don't understand why. :P

It would probably be useful for games that don't use Vanilla at all, too.

**Comment by Salynne** [comment]
I agree the command implement should go in vanilla, but the string lookup should be a feature of spout. Also I like your suggestion, we should space spaces with _ or something in the registry for easy command usage. Totally forgot about that.

**Comment by Salynne** [comment]
Closing this because I mostly forgot about it. The whole material system is being revamped currently and then following that the concept of a give command will have to be revisited. Sorry.

**Pull request closed without merging**
