### PR TITLE
Allow people to actually bind ip/port

### PR DESCRIPTION
**Pull request by katuma**
(unless theres plugin even for that which i might've missed?)

### CODE REVIEW

**Comment by zml2008** [comment]
Looks like this was missed when migrating to the updated configuration. Will test and pull.

**Comment by zml2008** [comment]
Hm, this doesn't seem to work. I changed the bind port with this fix and the server still attempted to use the default. Did this work for you?

**Comment by katuma** [comment]
sure, otherwise i'd not be sending a pull :)

you have to put something like this

address: 0.0.0.0:20000

in your config/config.yml

**Comment by zml2008** [comment]
ah, looks like somebody changed the config file while I wasn't looking. Your commit seems to fix the issue, but you'll have to commit it with the Signed-Off-By text (you can get this with git commit -s). More information about that is at http://forums.spout.org/threads/license-and-pull-requests.643/

**Comment by DrakiaXYZ** [comment]
But @zml2008 I need this so I can start the server (Alongside my main server), and I don't want to compile it myself! :P

**Comment by katuma** [comment]
lol zml2008, who needs signoffs ... cut&paste works as well for bukkit as spout! j/k, new pull against head

**Pull request merged**
