### PR TITLE
Replaced all SpoutAPI with the Spout Maths library

### PR DESCRIPTION
**Pull request by thehutch**
- Deleted all api maths utilities and classes
- Added Spout-Math to api pom

Signed-off-by:thehutch th3hutch@yahoo.co.uk

### CODE REVIEW

**Comment by macalinao** [comment]
We are American. It's math, not maths

**Comment by thehutch** [comment]
It's maths, deal with it https://www.youtube.com/watch?v=SbZCECvoaTA

**Comment by windy1** [comment]
That video seemed rather pro-"math".

**Comment by thehutch** [comment]
Moving PR to new-maths branch

**Pull request closed without merging**
