### PR TITLE
*Fast* packet listeners

### PR DESCRIPTION
**Pull request by Nightgunner5**
I'll write JavaDocs if you like it.

This way should be faster because it's not converting `int`s to `Integer` or doing `HashMap` lookups.

### CODE REVIEW

**Comment by Afforess** [comment]
Okay, I will test this when I get home from work, ~6PM EST.

**Comment by Raphfrk** [comment]
Actually, does sendPacket always happen in the main thread?  If not, then the listeners array needs to be synced in some way.  Otherwise, the addListeners and sendPacket could happen in different threads.

**Comment by Afforess** [comment]
> Actually, does sendPacket always happen in the main thread? If not, then the listeners array needs to be synced in some way. Otherwise, the addListeners and sendPacket could happen in different threads.

Fairly sure that it does not always happen in the main thread.

Locking with a Lock object would probably be fastest, even if it was more work.

**Comment by Raphfrk** [comment]
There is an AtomicReference<V> object.

Listener would be an array of atomic references to an array of listeners.

```
final AtomicReference<Listener[]>[] listeners = new AtomicReference<Listener[]>[256];
```

The check would be

```
checkSend(int packetId) {
    Listener[] l = listeners.get()[packetId];
    <rest of code>
}
```

Since only the main thread updates the listener, the update would never actually fail.

```
listeners[packetId].set(newArray);
```

However, the more complexity, the higher the load.

**Comment by Afforess** [comment]
Pulled for testing.

**Pull request merged**
