### PR TITLE
Added populated check

### PR DESCRIPTION
**Pull request by bergerkiller**
Signed-off-by: Irmo van den Berge bergerkiller@gmail.com
- To prevent a chunk being sent before it is populated.

### CODE REVIEW

**Comment by Raphfrk** [comment]
I don't think this is correct.  We still want to send updates if they happen to chunks pre-population?

**Comment by Zidane** [comment]
I think lighting needs to be calculated after all population that occurs in a chunk to prevent "double calculation" @Raphfrk

**Comment by Raphfrk** [comment]
Ok, but this blocks sending updates to the client completely.

**Comment by Zidane** [comment]
@Raphfrk hmmm

What do we do then? :p I noticed stuff like redstone is still working fine :S.

**Comment by Raphfrk** [comment]
I mean, it blocks sending any updates to non-populated chunks.

It isn't really critical, since presumably, populating the chunk will cause it to update anyway.

**Pull request merged**
