### PR TITLE
Made Keyboard enum more relieable on Macs.

### PR DESCRIPTION
**Pull request by narrowtux**
One key can now contain multiple key-codes, because some OSes tell different key-codes for keys like CMD, ALT or DELETE for example.

### CODE REVIEW

**Comment by narrowtux** [comment]
Oh, and deleted the LWIN and RWIN keys, because the were duplicated either way. When that's not okay, I can get them back...

**Comment by Afforess** [comment]
Don't have a mac - but I based this purely off the LWJGL Keyboard.class. Do mac's really report those values?

**Comment by narrowtux** [comment]
Yep.
I don't know if other users report the same problems, maybe I'm the only one but I don't think that.
Does it work with linux that way?

**Comment by Afforess** [comment]
Since it's your pull, it's your job to test and find out if linux treats it the same. ;)

Seriously though, if you can give me 1 more mac player to back this up, I'll pull it.

**Comment by K900** [comment]
The keycodes are the same on Linux. I've got an ATI GPU and I can't really test it because Minecraft runs on 5 fps with free drivers :(

**Comment by Afforess** [comment]
> The keycodes are the same on Linux.

To be clear, the same as narrowtux's or the existing configuration?

**Comment by K900** [comment]
Same as existing.

**Comment by Afforess** [comment]
@narrowtux

First off, I don't think key codes should ever be negative. If so, it's likely LWJGL's way of saying unknown. Secondly, the negative key codes are offsets of the originals. Look at the first one you changed. KEY_RMENU. 184-256 = -72. Coincidence? Nope. All of your codes do that.

One thing you can try is grabbing the latest LWJGL binaries and Java wrappers. Notch does not use the latest versions, but they work and may fix issues with OS X.

http://lwjgl.org/download.php

**Comment by K900** [comment]
That's probably some signed byte problem... again.

**Comment by Afforess** [comment]
> That's probably some signed byte problem... again.

I'm not familiar with LWJGL, are signed byte issues common? (Although the real WTF is as to why Java doesn't have unsigned primitives)

I could always compensate for those numbers manually, if need be.

**Comment by K900** [comment]
I ran into two or three. Though they're always the biggest pain with Java basic types :)

**Comment by Afforess** [comment]
Okay, should be fixed as of this commit, @narrowtux: https://github.com/SpoutDev/Spout/commit/0f36dd2576f1ac2a35e586babbc3f93aa9898ad3

**Pull request closed without merging**
