### PR TITLE
Added /teleport command. Allow custom kick message in stop command.

### PR DESCRIPTION
**Pull request by RafVDL**
This time without a screwed up commit :D

Added /teleport (alias: tp) command:
- Usage:
  /tp <playerfrom> <playerto>
  /tp <playerto> // Only from client.

Wrong number of arguments => blocked.

/shutdown [message]
All information in commit message :P
Tested (on commit 13e2c3ceff4a95b9b1ed163424670a27b5c5d512) and works, ofcourse.

### CODE REVIEW

**Comment by lukespragg** [comment]
Did not mean to close that. Wrong button. :/

**Comment by RafVDL** [comment]
Added /stop [message]
All information in commit message (ca31488) :P

**Comment by windy1** [comment]
Only concern is I'm unaware of how close Spout wants to stay to the vanila, otherwise, this could be a good idea, but also could be done as a plugin.

**Comment by aPunch** [comment]
It seems this is close enough to vanilla for Spout's tastes. I know some other commands are "less vanilla" than this.

**Pull request closed without merging**
