### PR TITLE
Generic fix

### PR DESCRIPTION
**Pull request by TomyLobo**
Fixed some warnings:
- Removed some "throws" declarations that are not actually thrown.
- Removed some redundant casts.

Some other changes:
- Improved NBTMapper methods.
- Fixed an asymmetry in TripleInt.equals.
- Replaced an "if (true) return" by /\* */
- Made some control flow easier to follow, mostly by extracting else bodies and flipping if/else conditions

### CODE REVIEW

**Comment by TomyLobo** [comment]
unit tests pass, no manual testing done yet

**Comment by Salynne** [comment]
Everything looks good so far. I carefully read every diff and agree with 90% of it and don't disagree with the rest. Let me know when you've got it manually tested.

**Comment by TomyLobo** [comment]
result of manual testing: https://github.com/VanillaDev/Vanilla/pull/235#issuecomment-6219093

**Comment by TomyLobo** [comment]
rebased to latest master and signed off all commits.

**Pull request merged**
