### PR TITLE
Added resync queue and PacketManager

### PR DESCRIPTION
**Pull request by Raphfrk**

### CODE REVIEW

**Comment by Afforess** [comment]
You can push this yourself. :p

**Comment by Raphfrk** [comment]
Yeah, was trying to get auto-merge to work :), rather than doing a direct push that incorporates a merge.

Anyway, this adds a PacketManager class and a sendImmediatePacket method.

```
packetManager = SpoutManager.getPacketManager();

packetManager.addListener(3, new PacketListenerClass());
```

Also, it is probably worth creating a super-class and have MCPacket and SpoutPacket as a sub-class

**Comment by Afforess** [comment]
> Also, it is probably worth creating a super-class and have MCPacket and SpoutPacket as a sub-class

Yeah, that's a good idea. I smell a GenericPacket. :p

**Comment by Raphfrk** [comment]
I reverted the queue part.  For some reason, it was causing a large holes in the map.

Also, but less important, resyncing back to the main thread adds an average of half a clock tick of latency (and there is no guarantee that there is a heart beat every server tick).

**Comment by Afforess** [comment]
Okay.

**Comment by Raphfrk** [comment]
Tracked down the issue to the active chunks variable being updated to late, so new chunks are dropped.

However, adding 1 tick of latency per packet may still not be a great plan.

**Pull request merged**
