### PR TITLE
Sends key-press events for every screen in multiplayer now.

### PR DESCRIPTION
**Pull request by narrowtux**
Also, fixed a fix of afforess in Keyboard.getKey() when client reports negative key-id.

### CODE REVIEW

**Comment by Afforess** [comment]
You can do this by just editing the GUIscreen class, which all popups extend, or intercepting them in minecraft.java instead of touching so many files

**Comment by narrowtux** [comment]
Hmm, that's true.
I may fix that tomorrow, will it get into spout 0.1 then?

**Comment by narrowtux** [comment]
Also, is there a way to get the player instance when you read data from a packet?
I'd like to do that to provide downwards compatibility.

**Comment by Afforess** [comment]
The player Id is given in the run method. If it is done in 24 hours it will be included

**Comment by narrowtux** [comment]
Is there any other way to provide backwards compatibility then? Because I send an additional int value in PacketKeyPress.

**Comment by Afforess** [comment]
> Is there any other way to provide backwards compatibility then? Because I send an additional int value in PacketKeyPress.

Normally, I'd suggest you subclass PacketKeyPress and use a new, similar packet. But this is one of the few instances where breaking things is not an issue, since we are changing the namespace anyway.

**Comment by halvors** [comment]
Could be possible to just take the entityid from packet and get entityid by that. Then just cast entity to player.

**Comment by narrowtux** [comment]
As of changing so many files, I made a new pull request!
https://github.com/SpoutDev/Spout/pull/90
I should use the branch feature more :D

**Pull request closed without merging**
