### PR TITLE
Replaced three-list system in SpoutScheduler

### PR DESCRIPTION
**Pull request by bergerkiller**
Signed-off-by: berger killer bergerkiller@gmail.com

Replaced the old/new/current lists with the new concurrent list version.

### CODE REVIEW

**Comment by Raphfrk** [comment]
It would be better to use atomics for the taskId counter, but granted the current implementation doesn't do that.

Why have a specific region task, why not just use the SpoutTask ?

Also, I could complain that you don't have delays/repeating tasks, but we can add that functionality if required.

**Comment by bergerkiller** [comment]
Yeah @Raphfrk This still needs more work. I want to include a SpoutScheduler in the region instead and give regions a 'getScheduler()'. I couldn't use SpoutTask as I had to use my own task ID and I couldn't access the pulse() function. But keep it open, will eventually get something more useful.

**Comment by bergerkiller** [comment]
Changed the PR a bit to make it more simplistic for now. Regions need a full-fledged scheduler which I rather leave up to you to make @Raphfrk

**Comment by Raphfrk** [comment]
One thing with the current scheduler is that it handles tick management and also async tasks.  The regions schedulers would would just be responsible for handling async task.  Maybe that could be split into 2 parts.

**Comment by bergerkiller** [comment]
@Raphfrk Exactly my thought, which was what I tried to do at some point. I guess we need a 'Scheduler' interface for sync stuff, and a 'MainScheduler' to add async scheduling.

**Pull request closed without merging**
