### PR TITLE
Replace all instances of <p/> with <p> to follow Oracle standards.

### PR DESCRIPTION
**Pull request by Grinch**
http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html#format

Signed-off-by: Steven Downer grinch@outlook.com

### CODE REVIEW

**Comment by Afforess** [comment]
This is still just as bad. < p > is the _opening tag_ of a paragraph. You also need to add _closing tags_ (< /p >) at the end of the paragraphs. Writing invalid html is not cool.

**Comment by Grinch** [comment]
Looking at the examples in that page they never once use the closing tag at all. Even in cases where there are multiple paragraphs.

**Comment by DDoS** [comment]
Grinch is right.

**Comment by Afforess** [comment]
Stackoverflow Agrees: http://stackoverflow.com/questions/5077382/javadoc-line-breaks-without-html-tags

It seems horrible. Such is life.

**Comment by macalinao** [comment]
HTML != XHTML

**Pull request merged**
