### PR TITLE
Add debugging of sent/received protocol codes. May be overly verbose.

### PR DESCRIPTION
**Pull request by Sleaker**
Signed-off-by: Nick Minkler sleaker@gmail.com

### CODE REVIEW

**Comment by zml2008** [comment]
Just uncomment https://github.com/SpoutDev/Spout/blob/master/api/src/main/java/org/spout/api/protocol/CommonHandler.java#L84 to print out packets sent/received.

**Comment by Sleaker** [comment]
@zml2008 - does that print opcodes?

**Comment by zml2008** [comment]
nope (opcodes aren't attached to Messages, they're attached to MessageCodecs), but why do you even need opcodes? (but anyway, you shouldn't be PR'ing active debug code this spammy (really, any at all), especially just a plain S.o.println of the codec's opcode).

**Comment by Sleaker** [comment]
Need to be able to debug incoming/outgoing Opcodes on the server to verify that they are matching up properly with the Vanilla client and the official MC server.

**Pull request closed without merging**
