### PR TITLE
Added the 'me' command

### PR DESCRIPTION
**Pull request by windy1**
I kept it pretty close to Vanilla, so open to interpretation and creativity for you guys ;)

### CODE REVIEW

**Comment by zml2008** [comment]
args.getJoinedStrings

**Comment by windy1** [comment]
Wow, I'm bad at this whole spacing thing :p

**Comment by windy1** [comment]
Well, I suck at git.. but I got it, if someone could kindly inform me how to merge these commits, that would be prime

**Comment by Zidane** [comment]
Why would only the player can do a me command? Why not let it say \* Console facepalms at the users of its' server

;)

**Comment by zml2008** [comment]
still no args.getJoinedStrings instead of args.getString

**Comment by narrowtux** [comment]
@NinjaZidane One the Reddit Childsplay Competition, I used /me once, it resulted in a comment about my scent.

**Comment by windy1** [comment]
@zml2008 Ik something came up, I'll add ASAP This is turning To be a fail of a pull

**Comment by windy1** [comment]
Okay, there

**Comment by windy1** [comment]
You know what, forget t :p

**Pull request closed without merging**
