### PR TITLE
Deleted duplicate dependencies

### PR DESCRIPTION
**Pull request by thehutch**
- Removed unnecessary test console spamming

Signed-off-by: thehutch th3hutch@yahoo.co.uk

### CODE REVIEW

**Comment by lukespragg** [comment]
They aren't all duplicate. Each project is using them in different ways, which is perfectly fine. The logging module does not need them all shaded into it, and you didn't actually make it do so with your changes. Either way they aren't hurting anything by being where they are now. Feel free to redo your PR with only the other PR purpose and don't worry about the dependencies.

**Comment by kitskub** [comment]
I don't see any changes...

**Comment by lukespragg** [comment]
I see no changes either. Please fix and correct your commit and PR description. As I said in my previous comment, don't worry about the dependencies, so that means remove the commit for those changes, and only keep the "Removed unnecessary test console spam".

**Comment by thehutch** [comment]
I did make changes, clearly you didn't look at the previous PR much :D. If they're duplicate depends why can't I remove them? I know last time I changed the logging depends to compile instead of provided but I changed that now it only removes the ones which for example are in Cerealization where they are made compile in their pom.xml.

**Comment by lukespragg** [comment]
They aren't duplicated dependencies, they are dependencies used by the associated modules in different ways. Nothing wrong with it, and your changes aren't really what I want to do with them. So for the third time, please do not worry about the dependencies.

I'm just going to close the PR though, again. Feel free to open a new one with just the other change as requested. In the future, please keep unrelated changes in separate PRs so this isn't a problem.

**Pull request closed without merging**
