### PR TITLE
Implement packet listeners

### PR DESCRIPTION
**Pull request by Nightgunner5**
Please note that I haven't tested this because I'm tired and I want to go to bed too

### CODE REVIEW

**Comment by Afforess** [comment]
I will test this this evening, to find out exactly how much it impacts performance.

**Comment by Afforess** [comment]
Any chance you can avoid completely destroying the formatting in the existing NSH code?

**Comment by Nightgunner5** [comment]
Stupid Eclipse

**Comment by Afforess** [comment]
Much better. I'm looking at it now.

**Comment by desmin88** [comment]
Yes! +9000 internets.

**Comment by Afforess** [comment]
After review, I am deciding against this.

2 main reasons:

1.) Performance. There is a lot of traffic, and this hurts the biggest servers the hardest. Not good.
2.) This listens to INCOMING packets from the client, not outgoing packets from the server. Most incoming packets already have some sort of event attached to them, I fail to see the need to block them. 

@desmin88 what you need for your project is an outgoing packet listener, so you can block the player specific packets from going to clients from the server. This pull is useless for you.

**Comment by Nightgunner5** [comment]
Sorry. I'm not an expert on packets in Minecraft. Which function would I override to listen for outgoing packets?

**Comment by Afforess** [comment]
NetServerHandler.sendPacket(Packet packet)

**Comment by Nightgunner5** [comment]
I should have asked sooner. It would have saved me a ton of work!

**Pull request merged**
