### PR TITLE
SPOUTAPI-27: Add load/generate options (allow load without generate for mapping)

### PR DESCRIPTION
**Pull request by mikeprimm**
See http://issues.spout.org/browse/SPOUTAPI-27 for details.  Depends upon https://github.com/SpoutDev/SpoutAPI/pull/201.

Signed-off-by: mikeprimm mike@primmhome.com

### CODE REVIEW

**Comment by Salynne** [comment]
I'm waiting on this because there is still a bunch of stuff messing with saving/loading in a branch.

**Comment by mikeprimm** [comment]
Sounds good - let me know if/when you need these rebased and/or retested

**Comment by Afforess** [comment]
I hate to be a stickler, but you need to squash your commits and need to signoff on your commit. Signing off indicates that you agree to the terms of our license.

**Comment by mikeprimm** [comment]
All good - I'll squash the commits.  What exactly do I need to do to "sign off"?  (I'm fine with doing it - just want to know the process)

**Comment by Salynne** [comment]
http://forums.spout.org/threads/pull-request-guidelines.2922/

**Comment by mikeprimm** [comment]
Cool - thanks for pointer.  Should be all set now, yes?

**Comment by windy1** [comment]
The commit is technically supposed to be signed off :p

**Comment by mikeprimm** [comment]
Was working off what I saw on every other signed pull - didn't see anything on folks commits

**Comment by Zidane** [comment]
Thanks a bunch @mikeprimm

**Comment by Raphfrk** [comment]
Not really a big deal, but it could make things clearer.

Look at how SaveState works in SpoutChunk

https://github.com/SpoutDev/Spout/blob/master/src/main/java/org/spout/engine/world/SpoutChunk.java

This is an enum that has return methods.  Having it as a separate enum is probably better than the way I did it though.

Anyway, you could have 

loadOpt.shouldLoad() - true if the chunk/region should be loaded, if not in memory
loadOpt.shouldGenerate() - true if the chunk/region should be generated, if non-existent

This is better than using ==

**Comment by mikeprimm** [comment]
@Raphfrk - That sounds cool - I'll mod it up tonight, and re-merge the changes

**Comment by Raphfrk** [comment]
@mikeprimm 

Great.  A nice thing about it is that it makes it easier to add extra fields to the enum without breaking code.

**Pull request merged**
