### PR TITLE
Implements ChatChannels

### PR DESCRIPTION
**Pull request by dredhorse**
PR for Implementing ChatChannels, see http://forums.spout.org/threads/chatchannels.5052/

Requires PR https://github.com/SpoutDev/SpoutAPI/pull/359

### CODE REVIEW

**Comment by dredhorse** [comment]
will fix the formatting.. thanks that nobody complained about the missing license up to now :-/

Todo List bespoken with @zml2008 :

Change Entity => CommandSource, will require plugin developers to add the CommandSource component to own entities
ChatMessageFormatting will be done with a MessageTemplate
Members of the ChatChannel will be moved into the ChatChannel object (Listining List) 
List of Channels a CommandSource is talking in will be moved into the ChatChannelComponent (Talking List)
Will use WeakReferences for the Listining List

That probably will remove the need for the ChatChannelManager in total.

Do we need a list of TALKING CommandSources in the ChatChannel object though?

**Comment by dredhorse** [comment]
I can't compile it... any Idea on how to fix that?

http://pastie.org/private/gepzizbrtihshmylqfpq7g

**Comment by Spouty** [comment]
**[AUTO-GENERATED COMMENT]**

This pull request has only **_1 commit**_ and is **_signed off**_.
Thanks for following the [pull request guidelines](http://spout.in/prguide) and for your contribution!
A [team member](http://spout.org/team) will review this pull request when time allows.

**Comment by dredhorse** [comment]
fixed and compiled

**Pull request closed without merging**
