### PR TITLE
Fix up the pom and the start of proper tree generation routines

### PR DESCRIPTION
**Pull request by md-5**
The name says it all. Refactors the pom to spoutdev, automatic downloading of jterminal. The treegens become more like notch code, with a separate generator for each type. Ive just added normal for the moment. It has workaround until we know what to do with events and blockstates. All details for the treegrow event is stored in an arraylist of blockstates and instead of calling the blockbuster.update it just manually loops through and sets them all.

### CODE REVIEW

**Comment by zml2008** [comment]
Would be great if you could replace all of your usages of Material with BlockID or ItemID and get/setTypeId. Lookup in Material is very slow, and speed is especially important in operations that occur frequently, such as tree generation.

**Comment by md-5** [comment]
@zml2008 

lol I had that but then I thought for changes to block id etc it would be better

**Comment by md-5** [comment]
done

**Comment by zml2008** [comment]
Well we're trying to have no dependencies on Bukkit as well (SpoutAPI is
going to replace Bukkit as a plugin API)

**Comment by md-5** [comment]
I can try and remove more, but at the moment they are only there because they are what Glowstone is passing around

**Comment by zml2008** [comment]
If Glowstone's passing them around, feel free to replace them with ID's

**Comment by md-5** [comment]
Well we're trying to have no dependencies on Bukkit as well (SpoutAPI is going to replace Bukkit as a plugin API)

Glowstone is passing round Bukkit types in a lot of places

**Comment by md-5** [comment]
redoing

**Pull request closed without merging**
