### PR TITLE
Added /teleport and /kill command

### PR DESCRIPTION
**Pull request by RafVDL**
Added vanilla teleport (alias: tp, tele) command to Spout.
/tp playerfrom playerto
or /tp playerto (if you run it from a client).

Both can be ran in the client, but only the first one in console.

Added vanilla kill command to Spout.
/kill

Only client, only OP.

The SpoutServer.java commit got screwed up :P

/me going to bed now :D

### CODE REVIEW

**Comment by md-5** [comment]
yeah, sightly screwed... might wanna fix it

**Comment by Zidane** [comment]
The kill command should be able to be used to kill another from the commandline.

Actually these commands should be able to...

Clientside
/tp NinjaGrinch should be able to tp me to NinjaGrinch
/tp NinjaGrinch NinjaMD5 should teleport NinjaGrinch to NinjaMD5
/kill should kill me
/kill NinjaGrinch should kill NinjaGrinch

Serverside
/tp and no player name should be blocked
/tp NinjaZidane NinjaGrinch should teleport NinjaZIdane to NinjaGrinch
/kill and no player name should be blocked
/kill NinjaGrinch should kill NinjaGrinch

**Comment by md-5** [comment]
Awe I'm a ninja
/me feels special

**Comment by RafVDL** [comment]
@NinjaZidane actually, the /tp command does what you describe. Github Flavored Markdown removed <> of the command example. :/

@md-5 I'll try to edit the screwed up commit in a few hours.

**Comment by RafVDL** [comment]
Going to restart, so that my local branch isn't screwed up.
You can manually merge this, if you want it :P

**Pull request closed without merging**
