### PR TITLE
Add /reload command. Addresses SPOUT-6.

### PR DESCRIPTION
**Pull request by aPunch**
This PR simply adds a /reload command to Spout. You can pass a plugin to the command if you just wish to reload one plugin.

Is it missing anything? Could the command have more options? Does more need to be reloaded?

### CODE REVIEW

**Comment by Top-Cat** [comment]
You've replaced all the tabs with spaces.

**Comment by aPunch** [comment]
Reverted funky formatting issues. It should be good to go formatting-wise, at least.

**Comment by Top-Cat** [comment]
Next up, wouldn't it be better to use an else instead of an if return?
I have a personal hatrid of if returns

**Comment by Afforess** [comment]
> Next up, wouldn't it be better to use an else instead of an if return?

It depends on how it's used. For instance, if return is better here:

```
if (foo) {
     return bar();
} else {
    return null;
}
```

vs

```
if (foo) {
     return bar();
}
return null;
```

But in this case, the return is breaking the standard flow. So yeah, if else would be nice.

**Comment by aPunch** [comment]
Fixed and rebased. What else needs to be changed? :P

**Comment by Salynne** [comment]
Looks good, thanks.

**Pull request merged**
