### PR TITLE
Eclipse Formatting

### PR DESCRIPTION
**Pull request by md-5**
.settings/org.eclipse.jdt.core.prefs

### CODE REVIEW

**Comment by Top-Cat** [comment]
See https://github.com/SpoutDev/Spout/pull/1265#issuecomment-3175004

**Comment by Afforess** [comment]
Gross.

**Comment by stephenwilliams** [comment]
lol @Afforess, my boss came to check wtf was going on because I randomly starting laughing when I read your comment

**Comment by stephenwilliams** [comment]
:P

**Pull request closed without merging**
